name: 'aicwd_dbt'
version: '1.0.0'
config-version: 2

profile: 'aicwd'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aicwd_dbt:
    staging:
      +materialized: view
    mart:
      +materialized: materialized_view
      +schema: mart
