// This file is auto-generated by Convex
// Do not edit directly

import type { TableDefinitions } from "convex/server";

const Tables = {
  logs: {
    doc_type: "log",
    timestamp: number,
    prompt: string,
    response: string,
    model: string,
    prompt_tokens: number,
    response_tokens: number,
    total_tokens: number,
    latency_ms: number,
    metadata?: {
      user_id?: string,
      session_id?: string,
      red_team_id?: string,
      prompt_category?: string,
      response_quality_score?: number,
      refused?: boolean,
    },
  },
  metrics: {
    doc_type: "metric",
    timestamp: number,
    metric_type: string,
    value: number,
    log_id: import("convex/server").Id<"logs">,
    metadata?: {
      semantic_units?: number,
      baseline_deviation?: number,
      adversarial_prompt?: string,
      coherence_score?: number,
      hallucination_probability?: number,
    },
  },
  redTeamRuns: {
    doc_type: "red_team_run",
    started_at: number,
    completed_at?: number,
    status: string,
    total_prompts: number,
    completed_prompts: number,
    success_count: number,
    refusal_count: number,
    avg_latency_ms?: number,
    total_tokens?: number,
    avg_cognitive_waste?: number,
    max_cognitive_waste?: number,
    model_endpoint: string,
  },
  adversarialResults: {
    doc_type: "adversarial_result",
    red_team_run_id: import("convex/server").Id<"redTeamRuns">,
    timestamp: number,
    prompt_type: string,
    adversarial_prompt: string,
    groq_response: string,
    response_tokens: number,
    latency_ms: number,
    refused: boolean,
    cognitive_waste: number,
    coherence_score: number,
    hallucination_probability: number,
    fragility_score: number,
  },
  baselineEmbeddings: {
    doc_type: "baseline_embedding",
    prompt: string,
    embedding: number[],
    category: string,
    created_at: number,
  },
  dbtRuns: {
    doc_type: "dbt_run",
    started_at: number,
    completed_at?: number,
    status: string,
    models_run: number,
    logs: string,
    error?: string,
  },
};

export type DataModel = TableDefinitions<typeof Tables>;
export const api = {
  ingestLog: {
    args: {
      prompt: string,
      response: string,
      model: string,
      prompt_tokens: number,
      response_tokens: number,
      total_tokens: number,
      latency_ms: number,
      metadata?: {
        user_id?: string,
        session_id?: string,
        red_team_id?: string,
        prompt_category?: string,
        response_quality_score?: number,
        refused?: boolean,
      },
    },
    returns: { success: boolean, log_id: import("convex/server").Id<"logs"> },
  },
  streamMetrics: {
    args: {},
    returns: {
      timestamp: number,
      logs: typeof Tables.logs[],
      metrics: {
        token_efficiency: typeof Tables.metrics[],
        semantic_drift: typeof Tables.metrics[],
        adversarial_stress: typeof Tables.metrics[],
        fragility_score: typeof Tables.metrics[],
      },
      red_team_status: typeof Tables.redTeamRuns | null,
      alerts: {
        cognitive_waste: typeof Tables.metrics[],
        semantic_drift: typeof Tables.metrics[],
      },
    },
  },
  startRedTeam: {
    args: {},
    returns: {
      success: boolean,
      run_id: import("convex/server").Id<"redTeamRuns">,
      success_count: number,
      refusal_count: number,
      avg_cognitive_waste: number,
    },
  },
  getRedTeamStatus: {
    args: { run_id?: import("convex/server").Id<"redTeamRuns"> },
    returns: typeof Tables.redTeamRuns | { status: string },
  },
  getRedTeamResults: {
    args: { run_id?: import("convex/server").Id<"redTeamRuns"> },
    returns: {
      results: typeof Tables.adversarialResults[],
      run_id: import("convex/server").Id<"redTeamRuns">,
    } | { results: [] },
  },
  scheduleDbtRun: {
    args: {},
    returns: { success: boolean, dbt_run_id: import("convex/server").Id<"dbtRuns"> },
  },
  runDbtScheduled: {
    args: {},
    returns: { skipped: boolean, reason: string } | { success: boolean, dbt_run_id: import("convex/server").Id<"dbtRuns"> },
  },
};
