// This file is auto-generated by Convex
// Do not edit directly

import type { ApiFromModules, DataModel } from "./dataModel";

export type DataModelType = DataModel;

// Re-export types from convex/server
import { mutation, query, action, internalMutation, internalQuery, internalAction } from "convex/server";

export { mutation, query, action, internalMutation, internalQuery, internalAction };
